### ISSUE TITLE
dg2_dmc_ver2_07.bin missing

### ISSUE THREAD

**Issue by spyfly** [intel-gpu/intel-gpu-firmware#2]
DG2 DMC Ver2_07 Firmware is missing in this repository, even thought it is depended on by the latest version of: https://github.com/intel-gpu/intel-gpu-i915-backports/tree/ubuntu/main

Linux-Kernel source also contains the Ver2_07 DMC Firmware: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/i915/dg2_dmc_ver2_07.bin

**Comment by ArturKloniecki** [comment]
Missing binary has been added.
